server:
  port: 8080
spring:
  application:
    name: web-service
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ypg?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 8.142.12.101
    username: admin
    password: admin

  redis:
    host: 8.142.12.101
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 0
    timeout: 2000ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

#mybatis的相关配置

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liu.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  not-empty: true
  mappers: tk.mybatis.mapper.common.Mapper